In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train = pd.read_csv("E:\Analytics Vidhya\Loan Prediction\Train_Data.csv")
test = pd.read_csv("E:\Analytics Vidhya\Loan Prediction\Test_Data.csv")

In [3]:
data = pd.concat([train,test], axis =0)

In [4]:
data

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001002   Male      No          0      Graduate            No   
1    LP001003   Male     Yes          1      Graduate            No   
2    LP001005   Male     Yes          0      Graduate           Yes   
3    LP001006   Male     Yes          0  Not Graduate            No   
4    LP001008   Male      No          0      Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
362             4009             1777.0       113.0             360.0   
363             4158              709.0       115.0             360.0   
364             3250             1993.0       126.0             360.0   
365             5000             2393.0       158.0             360.0   
366             9200                0.0        98.0             180.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
362             1.0         Urban         NaN  
363             1.0         Urban         NaN  
364             NaN     Semiurban         NaN  
365             1.0         Rural         NaN  
366             1.0         Rural         NaN  

[981 rows x 13 columns]

In [5]:
data.isnull().sum()

Loan_ID                0
Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term      20
Credit_History        79
Property_Area          0
Loan_Status          367
dtype: int64

In [6]:
data.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       981.000000         981.000000  954.000000        961.000000   
mean       5179.795107        1601.916330  142.511530        342.201873   
std        5695.104533        2718.772806   77.421743         65.100602   
min           0.000000           0.000000    9.000000          6.000000   
25%        2875.000000           0.000000  100.000000        360.000000   
50%        3800.000000        1110.000000  126.000000        360.000000   
75%        5516.000000        2365.000000  162.000000        360.000000   
max       81000.000000       41667.000000  700.000000        480.000000   

       Credit_History  
count      902.000000  
mean         0.835920  
std          0.370553  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 981 entries, 0 to 366
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            981 non-null    object 
 1   Gender             957 non-null    object 
 2   Married            978 non-null    object 
 3   Dependents         956 non-null    object 
 4   Education          981 non-null    object 
 5   Self_Employed      926 non-null    object 
 6   ApplicantIncome    981 non-null    int64  
 7   CoapplicantIncome  981 non-null    float64
 8   LoanAmount         954 non-null    float64
 9   Loan_Amount_Term   961 non-null    float64
 10  Credit_History     902 non-null    float64
 11  Property_Area      981 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 107.3+ KB


In [8]:
loan_status_map = {'Y':1,'N':0}
data['Loan_Status'] = data['Loan_Status'].map(loan_status_map)

In [9]:
data.Loan_Status.value_counts()

1.0    422
0.0    192
Name: Loan_Status, dtype: int64

In [10]:
data['Loan_Status'] = data['Loan_Status'].fillna(1.0)

In [11]:
data.Loan_Status.isnull().sum()

0

In [12]:
data['Gender'] = data['Gender'].fillna('Male')

In [13]:
data.Gender.isnull().sum()

0

In [14]:
data.Gender.value_counts()

Male      799
Female    182
Name: Gender, dtype: int64

In [15]:
gender_map = {'Male':0,'Female':1}
data['Gender'] = data['Gender'].map(gender_map)

In [16]:
data['Married'] = data['Married'].fillna('Yes')

In [17]:
data.Married.isnull().sum()

0

In [18]:
married_map = {'Yes':1,'No':0}
data['Married'] = data['Married'].map(married_map)

In [19]:
data.Married.value_counts()

1    634
0    347
Name: Married, dtype: int64

In [20]:
dependent_map = {'0':0,'1':1,'2':2,'3+':3}
data['Dependents'] = data['Dependents'].map(dependent_map)

In [21]:
data['Dependents'].value_counts()

0.0    545
2.0    160
1.0    160
3.0     91
Name: Dependents, dtype: int64

In [22]:
data['Dependents'] = data['Dependents'].fillna(0.0)

In [23]:
data['Dependents'].isnull().sum()

0

In [24]:
Education_map = {'Graduate':1,'Not Graduate':0}
data['Education'] = data.Education.map(Education_map)

In [25]:
data['Self_Employed'] = data['Self_Employed'].fillna('No')

In [26]:
Self_Employed_map = {'Yes':1,'No':0}
data['Self_Employed'] = data['Self_Employed'].map(Self_Employed_map)

In [27]:
data['LoanAmount'] = data['LoanAmount'].fillna(data['LoanAmount'].mean())

In [28]:
data['Loan_Amount_Term'] = data['Loan_Amount_Term'].fillna(data['Loan_Amount_Term'].mean())

In [29]:
data['Credit_History'] = data['Credit_History'].fillna(1.0)

In [30]:
Property_Area_map = {'Semiurban':0,'Urban':1,'Rural':2}
data['Property_Area'] = data['Property_Area'].map(Property_Area_map)

In [31]:
data = data.drop('Loan_ID', axis = 1)

In [32]:
x = data.drop('Loan_Status', axis = 1)
y = data.Loan_Status

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test ,y_train,y_test = train_test_split(x,y,train_size = 0.7, random_state= 42)

In [35]:
x_train.shape

(686, 11)

In [36]:
y_train.shape

(686,)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
log_model = LogisticRegression()
log_model.fit(x_train, y_train)

LogisticRegression()

In [39]:
log_model.score(x_train, y_train)

0.814868804664723

In [40]:
log_pred = log_model.predict(x_test)

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [42]:
log_accuracy_score = accuracy_score(y_test, log_pred)
log_accuracy_score

0.7932203389830509

In [43]:
cm = confusion_matrix(y_test, log_pred)
cm

array([[  4,  59],
       [  2, 230]], dtype=int64)

In [44]:
from sklearn.tree import DecisionTreeClassifier

In [45]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
dt_model.score(x_train, y_train)

1.0

In [46]:
dt_model.score(x_test, y_test)

0.7491525423728813

In [47]:
dt_pred = dt_model.predict(x_test)

In [48]:
cm = confusion_matrix(y_test, dt_pred)
cm

array([[ 20,  43],
       [ 31, 201]], dtype=int64)

In [49]:
dt_score = accuracy_score(y_test, dt_pred)
dt_score

0.7491525423728813

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)
rf_pred = rf_model.predict(x_test)

In [52]:
rf_model.score(x_train, y_train)

1.0

In [53]:
rf_model.score(x_test, y_test)

0.8033898305084746

In [54]:
rf_cm = confusion_matrix(y_test, rf_pred)
rf_cm

array([[ 14,  49],
       [  9, 223]], dtype=int64)

In [55]:
rf_score = accuracy_score(y_test, rf_pred)
rf_score

0.8033898305084746

In [56]:
from sklearn.model_selection import RandomizedSearchCV

In [57]:
 #Randomized Search CV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]


In [58]:
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}


In [59]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,scoring='neg_mean_squared_error', 
                               n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

In [60]:
rf_random.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.7s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   2.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   2.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimator

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [61]:
rf_random.best_params_

{'n_estimators': 1100,
 'min_samples_split': 10,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 15}

In [62]:
rf_random.best_score_

-0.16323918332804402

In [63]:
predictions=rf_random.predict(x_test)

In [64]:
rf_cm = confusion_matrix(y_test, predictions)
rf_cm

array([[ 11,  52],
       [  9, 223]], dtype=int64)

In [65]:
rf_score = accuracy_score(y_test, predictions)
rf_score

0.7932203389830509

In [66]:
Submission_data = pd.read_csv("E:\Analytics Vidhya\Loan Prediction\sample_submission.csv")
Submission_data

Loan_ID Loan_Status
0    LP001015           N
1    LP001022           N
2    LP001031           N
3    LP001035           N
4    LP001051           N
..        ...         ...
362  LP002971           N
363  LP002975           N
364  LP002980           N
365  LP002986           N
366  LP002989           N

[367 rows x 2 columns]

In [67]:
predictions

array([1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [68]:
predictions =pd.Series(predictions)
predictions

0      1.0
1      1.0
2      1.0
3      1.0
4      0.0
      ... 
290    1.0
291    1.0
292    1.0
293    1.0
294    1.0
Length: 295, dtype: float64

In [69]:
Submission_data['Loan_Status'] = predictions

In [70]:
Submission_data

Loan_ID  Loan_Status
0    LP001015          1.0
1    LP001022          1.0
2    LP001031          1.0
3    LP001035          1.0
4    LP001051          0.0
..        ...          ...
362  LP002971          NaN
363  LP002975          NaN
364  LP002980          NaN
365  LP002986          NaN
366  LP002989          NaN

[367 rows x 2 columns]

In [71]:
loan_status_map = {1:'Y',0:'N'}
Submission_data['Loan_Status'] = Submission_data['Loan_Status'].map(loan_status_map)

In [72]:
Submission_data

Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           Y
2    LP001031           Y
3    LP001035           Y
4    LP001051           N
..        ...         ...
362  LP002971         NaN
363  LP002975         NaN
364  LP002980         NaN
365  LP002986         NaN
366  LP002989         NaN

[367 rows x 2 columns]

In [73]:
Submission_data.to_csv (r'E:\Analytics Vidhya\Loan Prediction\Submission_data_randomsearch.csv',
                        index = False, header=True)
